import {normalizeProjects} from './project-content.js';
(()=>{
const dialog=document.getElementById('artifact-view'),visual=document.getElementById('artifact-visual'),count=document.getElementById('artifact-count');let project=null,mediaIndex=0,opener=null;
const fallbackProjects=()=>[...document.querySelectorAll('.discovery')].map(el=>({title:el.querySelector('h3').textContent,description:el.querySelector('.discovery-copy > p').textContent,links:[...el.querySelectorAll('.project-links a')].map(a=>({url:a.href,label:a.textContent.replace(' ↗','')})),tags:[...el.querySelectorAll('.tags span')].map(x=>x.textContent),media:[{src:null,caption:'Screenshot coming soon'}]}));
const dataPromise=fetch('./content.json').then(r=>{if(!r.ok)throw Error('Content unavailable');return r.json()}).then(d=>normalizeProjects(d.projects)).catch(fallbackProjects);
function placeholder(){const el=document.createElement('div');el.className='placeholder-art';const cross=document.createElement('span');cross.className='artifact-cross';cross.textContent='✧';const words=document.createElement('span');words.className='placeholder-word';words.append('A WINDOW INTO');const title=document.createElement('em');title.textContent=project.title;words.append(title);const status=document.createElement('span');status.className='placeholder-status';status.textContent='SCREENSHOT COMING SOON';el.append(cross,words,status);return el;}
function renderMedia(){visual.replaceChildren();const items=project.media?.length?project.media:[{src:null}];const item=items[mediaIndex];if(item.src){const img=new Image();img.alt=item.alt||project.title+' screenshot';img.addEventListener('error',()=>visual.replaceChildren(placeholder()),{once:true});img.src=item.src;visual.append(img)}else visual.append(placeholder());count.textContent=items.length>1?`${mediaIndex+1} / ${items.length}`:(item.src?item.caption||'Project screenshot':'Screenshot placeholder');document.getElementById('artifact-prev').hidden=document.getElementById('artifact-next').hidden=items.length<2;}
async function open(button){const projects=await dataPromise;project=projects[Number(button.dataset.project)];if(!project)return;opener=button;mediaIndex=0;document.getElementById('artifact-title').textContent=project.title;document.getElementById('artifact-description').textContent=project.description;const technologies=document.getElementById('artifact-technologies');technologies.replaceChildren();for(const tag of project.tags){const span=document.createElement('span');span.textContent=tag;technologies.append(span)}const links=document.getElementById('artifact-links');links.replaceChildren();for(const link of project.links){const a=document.createElement('a');a.href=link.url;a.textContent=link.label+' ↗';a.className='project-link';a.target='_blank';a.rel='noopener noreferrer';links.append(a)}renderMedia();document.body.classList.add('artifact-opened');dialog.showModal();}
document.querySelectorAll('.artifact-open').forEach(button=>button.addEventListener('click',()=>open(button)));document.getElementById('artifact-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.classList.remove('artifact-opened');opener?.focus({preventScroll:true});window.dispatchEvent(new Event('voyage-resume'))});function next(delta){const n=project?.media?.length||1;mediaIndex=(mediaIndex+delta+n)%n;renderMedia()}document.getElementById('artifact-next').addEventListener('click',()=>next(1));document.getElementById('artifact-prev').addEventListener('click',()=>next(-1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();next(e.key==='ArrowRight'?1:-1)}});
// Readable compositions track the nearest narrative moment, with no queued reveals.
const moments=[...document.querySelectorAll('.spatial-moment')];let pending=0;
function sync(){pending=0;const center=innerHeight*.53;let nearest=null,distance=Infinity;for(const el of moments){const r=el.getBoundingClientRect(),d=Math.abs(r.top+r.height/2-center);if(d<distance){distance=d;nearest=el;}if(el.classList.contains('discovery'))el.style.setProperty('--artifact-drift',Math.max(-32,Math.min(32,(r.top-center)*.045))+'px');}const active=nearest&&nearest.getBoundingClientRect().top<innerHeight*.85&&nearest.getBoundingClientRect().bottom>innerHeight*.2;let right=0;for(const el of moments){if(el.dataset.side!=='right')continue;const r=el.getBoundingClientRect();const t=Math.max(0,Math.min(1,(innerHeight*.9-r.top)/(innerHeight*.45),(r.bottom-innerHeight*.1)/(innerHeight*.45)));right=Math.max(right,t*t*(3-2*t));}document.body.style.setProperty('--right-copy',right);window.voyageComposition=1-2*right;}
function schedule(){if(!pending)pending=requestAnimationFrame(sync)}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);sync();
})();

