(()=>{'use strict';const root=document.documentElement,header=document.querySelector('header'),sections=[...document.querySelectorAll('.chapter')],cards=[...document.querySelectorAll('.project')],dialog=document.querySelector('#world-map'),motion=document.querySelector('#motion'),pref=matchMedia('(prefers-reduced-motion: reduce)'),hero=document.querySelector('.hero-scene');let enabled=!pref.matches,frame=0,opener=null;const clamp=x=>Math.max(0,Math.min(1,x));
const reveals=[...document.querySelectorAll('.about-copy,.skill,.section-intro,.logbook article,.contact-content')];const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');observer.unobserve(e.target)}}),{threshold:.08});reveals.forEach((e,i)=>{e.classList.add('reveal');e.style.transitionDelay=`${e.classList.contains('skill')?(i%2)*80:0}ms`;observer.observe(e)});
function measure(){cards.forEach(c=>c.classList.toggle('can-pin',enabled&&innerWidth>=1100&&c.offsetHeight<innerHeight-145));schedule()}
function paint(){frame=0;const progress=clamp(scrollY/Math.max(1,root.scrollHeight-innerHeight));root.style.setProperty('--progress',progress);root.style.setProperty('--bearing',`${progress*300}deg`);document.querySelector('.rail-ship').style.top=`${progress*100}%`;header.classList.toggle('scrolled',scrollY>60);let current=sections[0];sections.forEach(s=>{if(s.getBoundingClientRect().top<innerHeight*.42)current=s});document.querySelector('#location').textContent=current.dataset.location;document.querySelector('#chapter-count').textContent=current.dataset.number+' / 06';document.querySelectorAll('.map-route a,.voyage-rail a').forEach(a=>{if(a.hash==='#'+current.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')});if(!enabled)return;const hp=clamp(scrollY/sections[0].offsetHeight);hero.style.transform=`translateY(${hp*(innerWidth>600?100:40)}px) scale(${1+hp*.045})`;cards.forEach((c,i)=>{const next=cards[i+1];const p=next&&c.classList.contains('can-pin')?clamp((innerHeight-next.getBoundingClientRect().top)/(innerHeight-110)):0;c.style.setProperty('--scale',1-p*.035)})}
function schedule(){if(!frame)frame=requestAnimationFrame(paint)}
function setMotion(value){enabled=value;root.classList.toggle('js-motion',value);root.classList.toggle('motion-off',!value);motion.textContent=value?'Motion on':'Motion off';motion.setAttribute('aria-pressed',String(value));hero.style.transform='';cards.forEach(c=>c.style.removeProperty('--scale'));measure()}
motion.addEventListener('click',()=>setMotion(!enabled));pref.addEventListener('change',()=>setMotion(!pref.matches));addEventListener('scroll',schedule,{passive:true});addEventListener('resize',measure,{passive:true});document.fonts.ready.then(measure);new ResizeObserver(measure).observe(document.querySelector('.project-route'));
document.querySelectorAll('.map-open').forEach(button=>button.addEventListener('click',()=>{opener=button;dialog.showModal();document.body.style.overflow='hidden'}));function close(){dialog.close()}document.querySelector('#map-close').addEventListener('click',close);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});dialog.addEventListener('close',()=>{document.body.style.overflow='';opener?.focus({preventScroll:true})});document.querySelectorAll('.map-route a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();close();const target=document.querySelector(a.hash);history.pushState(null,'',a.hash);target.scrollIntoView({behavior:enabled?'smooth':'instant'});target.setAttribute('tabindex','-1');target.focus({preventScroll:true})}));setMotion(enabled);
})();
